apiVersion: v1
kind: Service
metadata:
  name: portfolio-website-svc
spec:
  selector:
    app: portfolio-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # or LoadBalancer if you want direct IP