replicaCount: 2

image:
  repository: chandru/portfolio-website
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
# - name: acr-secret

containerPort: 80

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: ""  # e.g., "nginx" or "traefik"
  host: portfolio.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    enabled: false

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60