apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "portfolio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "portfolio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.containerPort }}
      protocol: TCP
      name: http